services:

  petname:
    image: petname:latest
    build: petname
    container_name: petname
    restart: unless-stopped
    ports:
      - 28081:8080
    environment:
      - PETNAME_GRPC_PORT=8080

  tests:
    image: tests:latest
    build: tests
    container_name: tests
    restart: "no"
    entrypoint: "true"
